name: Clean & sort

on:
  push:
    branches: [ master ]

jobs:
  clean-sort:
    
    name: Clean and sort files

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17

      - name: Give permissions
        run: chmod +x "./.github/compile_run.sh"

      - name: Run clean
        run:  ./.github/compile_run.sh clean
      
      - name: Commit & push clean
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          if ! git diff --exit-code; then
            git add -A
            git commit -m "Clean files action"
            git push -f origin master
          fi
      
      - name: Run sort
        run: ./.github/compile_run.sh sort

      - name: Commit & push sort
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          if ! git diff --exit-code; then
            git add -A
            git commit -m "Sort files action"
            git push -f origin master
          fi